version: '3.3'

services:
  portfolio-app:
    image: ${DOCKER_USERNAME}/portfolio:latest
    container_name: portfolio_web
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"  # Added for health check fallback
    restart: unless-stopped
    volumes:
      - /secure/portfolio/resume:/app/static/secure:ro
      - /var/log/portfolio:/app/logs
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - RESUME_PATH=static/secure
      - RESUME_FILENAME=Jaques_Burger_Resume.pdf
      - SECRET_KEY=${SECRET_KEY:-fallback-secret-key}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - SSL_CERT_PATH=/etc/letsencrypt/live/jaquesburger.com/fullchain.pem
      - SSL_KEY_PATH=/etc/letsencrypt/live/jaquesburger.com/privkey.pem
    networks:
      - portfolio_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:443/health", "--insecure"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  portfolio_network:
    driver: bridge
    name: portfolio_network