version: '3.3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-site.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - portfolio-app
    restart: unless-stopped
    networks:
      - portfolio_network

  portfolio-app:
    image: ${DOCKER_USERNAME}/portfolio:latest
    container_name: portfolio_web
    expose:
      - "5000"  # Internal only, not published
    restart: unless-stopped
    volumes:
      - /secure/portfolio/resume:/app/static/secure:ro
      - /var/log/portfolio:/app/logs
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - RESUME_PATH=static/secure
      - RESUME_FILENAME=Jaques_Burger_Resume.pdf
      - SECRET_KEY=${SECRET_KEY:-fallback-secret-key}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge
    name: portfolio_network